---
abstract: 'manage linked css and js'
author:
  - 'Yaroslav Korshak  C<< <ykorshak@gmail.com> >>'
  - 'Yaroslav Korshak <yko@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.57
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.57
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-LinkedContent
no_index:
  directory:
    - inc
    - t
requires:
  Mojolicious: 1.01
  perl: 5.10.0
resources:
  bugtracker: https://github.com/yko/mojolicious-plugin-linkedcontent/issues
  license: http://dev.perl.org/licenses
  repository: https://github.com/yko/mojolicious-plugin-linkedcontent
version: 0.04
